// The plain Worker entry the test runner drives: the routes plus the two
// Durable Objects and the Workflow, with no Flue bootstrap. The deployed
// Worker is generated by the Vite pipeline from src/app.ts and
// src/cloudflare.ts instead.
export { default } from "./app.ts";
export * from "./cloudflare.ts";
